const iso = (value) => value.toISOString().slice(0, 10);

const referenceDate = new Date('2026-05-25T12:00:00');
const daysAgo = (days) => iso(new Date(referenceDate.getTime() - days * 86400000));
const daysAhead = (days) => iso(new Date(referenceDate.getTime() + days * 86400000));

const money = (value) => value;

export const demoEmpresa = {
  id: 'empresa-demo-supremo',
  nome: 'Auto Center Supremo',
  slug: 'supremo',
  telefone: '(11) 99234-5678',
  whatsapp: '5511992345678',
  email: 'contato@autocentersupremo.com.br',
  endereco: 'Av. das Industrias, 1.420 - Sao Paulo, SP',
  slogan: 'Controle total da oficina com IA aplicada ao dia a dia.',
  sobre: 'Oficina focada em revisão preventiva, diagnóstico, freios, suspensão, elétrica e atendimento consultivo para clientes particulares e frotas leves.',
  cor_primaria: '#1C3F5E',
  plano: 'Profissional',
  anos_mercado: 12,
  vitrine_ativa: true,
};

export const demoClientes = [
  {
    id: 'cli-ricardo',
    nome: 'Ricardo Almeida',
    telefone: '(11) 98765-4321',
    email: 'ricardo.almeida@email.com',
    status: 'ativo',
    tags: ['VIP', 'Recorrente'],
    veiculos_count: 2,
    total_gasto: money(4780),
    ultima_visita: daysAgo(12),
    observacoes: 'Cliente recorrente, aprova revisões preventivas sem demora.',
  },
  {
    id: 'cli-fernanda',
    nome: 'Fernanda Costa',
    telefone: '(11) 97654-3210',
    email: 'fernanda.costa@email.com',
    status: 'inativo',
    tags: ['Inativo'],
    veiculos_count: 1,
    total_gasto: money(1840),
    ultima_visita: '2026-01-05',
    observacoes: 'Cliente sumiu após recorrência de problema no ar-condicionado.',
  },
  {
    id: 'cli-marcelo',
    nome: 'Marcelo Souza',
    telefone: '(11) 91234-5678',
    email: 'marcelo.souza@frotasms.com.br',
    status: 'ativo',
    tags: ['VIP', 'Frota'],
    veiculos_count: 1,
    total_gasto: money(6320),
    ultima_visita: daysAgo(2),
    observacoes: 'Responsável por veículo de frota empresarial.',
  },
  {
    id: 'cli-juliana',
    nome: 'Juliana Martins',
    telefone: '(11) 95555-9999',
    email: 'juliana.martins@email.com',
    status: 'ativo',
    tags: ['Ativo'],
    veiculos_count: 1,
    total_gasto: money(1380),
    ultima_visita: daysAgo(8),
    observacoes: 'Valoriza rapidez e atualização por WhatsApp.',
  },
  {
    id: 'cli-carlos',
    nome: 'Carlos Eduardo Ramos',
    telefone: '(11) 94444-8888',
    email: 'carlos.ramos@email.com',
    status: 'inativo',
    tags: ['Inativo'],
    veiculos_count: 0,
    total_gasto: money(960),
    ultima_visita: daysAgo(136),
    observacoes: 'Inativo há mais de 130 dias. Forte chance de recuperação com oferta.',
  },
  {
    id: 'cli-patricia',
    nome: 'Patricia Lima',
    telefone: '(11) 93333-7777',
    email: 'patricia.lima@email.com',
    status: 'ativo',
    tags: ['Recorrente'],
    veiculos_count: 1,
    total_gasto: money(2780),
    ultima_visita: daysAgo(4),
    observacoes: 'Cliente fiel de manutenção programada.',
  },
];

export const demoVeiculos = [
  {
    id: 'vei-corolla',
    cliente_id: 'cli-ricardo',
    cliente_nome: 'Ricardo Almeida',
    marca: 'Toyota',
    modelo: 'Corolla',
    ano: 2021,
    placa: 'BRA-2E19',
    cor: 'Prata',
    quilometragem: 48200,
    ultima_revisao: daysAgo(94),
    proxima_revisao: daysAhead(38),
    observacoes: 'Uso urbano diário.',
    historico_count: 5,
  },
  {
    id: 'vei-hrv',
    cliente_id: 'cli-ricardo',
    cliente_nome: 'Ricardo Almeida',
    marca: 'Honda',
    modelo: 'HR-V',
    ano: 2022,
    placa: 'GHI-4J22',
    cor: 'Branco',
    quilometragem: 22100,
    ultima_revisao: daysAgo(60),
    proxima_revisao: daysAhead(14),
    observacoes: 'Perto da revisão dos 25.000 km.',
    historico_count: 3,
  },
  {
    id: 'vei-polo',
    cliente_id: 'cli-fernanda',
    cliente_nome: 'Fernanda Costa',
    marca: 'VW',
    modelo: 'Polo',
    ano: 2020,
    placa: 'DEF-5K20',
    cor: 'Vermelho',
    quilometragem: 61000,
    ultima_revisao: daysAgo(140),
    proxima_revisao: daysAhead(9),
    observacoes: 'Frequente problema no ar-condicionado.',
    historico_count: 4,
  },
  {
    id: 'vei-s10',
    cliente_id: 'cli-marcelo',
    cliente_nome: 'Marcelo Souza',
    marca: 'Chevrolet',
    modelo: 'S10',
    ano: 2023,
    placa: 'JKL-7M23',
    cor: 'Preto',
    quilometragem: 35400,
    ultima_revisao: daysAgo(33),
    proxima_revisao: daysAhead(41),
    observacoes: 'Frota empresarial.',
    historico_count: 6,
  },
  {
    id: 'vei-pulse',
    cliente_id: 'cli-juliana',
    cliente_nome: 'Juliana Martins',
    marca: 'Fiat',
    modelo: 'Pulse',
    ano: 2023,
    placa: 'MNO-8P23',
    cor: 'Azul',
    quilometragem: 18700,
    ultima_revisao: daysAgo(22),
    proxima_revisao: daysAhead(62),
    observacoes: 'Uso leve em cidade.',
    historico_count: 2,
  },
  {
    id: 'vei-compass',
    cliente_id: 'cli-patricia',
    cliente_nome: 'Patricia Lima',
    marca: 'Jeep',
    modelo: 'Compass',
    ano: 2022,
    placa: 'PQR-9S22',
    cor: 'Cinza',
    quilometragem: 42000,
    ultima_revisao: daysAgo(17),
    proxima_revisao: daysAhead(27),
    observacoes: 'Cliente faz revisão preventiva semestral.',
    historico_count: 5,
  },
];

const item = (descricao, quantidade, valor, status = 'pendente') => ({ descricao, quantidade, valor, status });

export const demoOrcamentos = [
  {
    id: 'orc-041',
    numero: 'ORC-2026-041',
    status: 'aprovado',
    total: money(1850),
    cliente_id: 'cli-marcelo',
    cliente_nome: 'Marcelo Souza',
    veiculo_id: 'vei-s10',
    veiculo_desc: 'Chevrolet S10 2023 - JKL-7M23',
    data: daysAgo(3),
    validade: daysAhead(7),
    itens: [item('Troca de óleo', 1, 320), item('Freios', 1, 640), item('Alinhamento', 1, 210), item('Mão de obra', 1, 680)],
    observacoes: 'Aprovado e liberado para execução imediata.',
  },
  {
    id: 'orc-042',
    numero: 'ORC-2026-042',
    status: 'pendente',
    total: money(2340),
    cliente_id: 'cli-ricardo',
    cliente_nome: 'Ricardo Almeida',
    veiculo_id: 'vei-corolla',
    veiculo_desc: 'Toyota Corolla 2021 - BRA-2E19',
    data: daysAgo(4),
    validade: daysAhead(4),
    itens: [item('Correia dentada', 1, 920), item('Bomba d\'água', 1, 760), item('Fluido', 1, 140), item('Mão de obra', 1, 520)],
    observacoes: 'Cliente visualizou e ainda não respondeu.',
  },
  {
    id: 'orc-039',
    numero: 'ORC-2026-039',
    status: 'aprovado',
    total: money(780),
    cliente_id: 'cli-patricia',
    cliente_nome: 'Patricia Lima',
    veiculo_id: 'vei-compass',
    veiculo_desc: 'Jeep Compass 2022 - PQR-9S22',
    data: daysAgo(10),
    validade: daysAgo(2),
    itens: [item('Troca de óleo', 1, 290), item('Filtro', 1, 140), item('Mão de obra', 1, 350)],
    observacoes: 'Convertido em OS e pago.',
  },
  {
    id: 'orc-038',
    numero: 'ORC-2026-038',
    status: 'recusado',
    total: money(1200),
    cliente_id: 'cli-juliana',
    cliente_nome: 'Juliana Martins',
    veiculo_id: 'vei-pulse',
    veiculo_desc: 'Fiat Pulse 2023 - MNO-8P23',
    data: daysAgo(14),
    validade: daysAgo(5),
    itens: [item('Serviço ar-condicionado', 1, 520), item('Gás refrigerante', 1, 280), item('Mão de obra', 1, 400)],
    observacoes: 'Cliente achou caro e adiou.',
  },
];

export const demoOrdens = [
  {
    id: 'os-091',
    numero: 'OS-2026-091',
    status: 'em_andamento',
    pagamento_status: 'parcial',
    cliente_id: 'cli-marcelo',
    cliente_nome: 'Marcelo Souza',
    veiculo_id: 'vei-s10',
    veiculo_desc: 'Chevrolet S10 2023 - JKL-7M23',
    tecnico: 'Paulo Henrique',
    prioridade: 'alta',
    total: money(1850),
    data_abertura: daysAgo(2),
    data_conclusao: null,
    observacoes: 'Serviço em andamento na bancada 2.',
    itens: [
      item('Troca de óleo', 1, 320, 'concluido'),
      item('Freios', 1, 640, 'em_andamento'),
      item('Alinhamento', 1, 210, 'pendente'),
    ],
  },
  {
    id: 'os-090',
    numero: 'OS-2026-090',
    status: 'concluida',
    pagamento_status: 'pago',
    cliente_id: 'cli-patricia',
    cliente_nome: 'Patricia Lima',
    veiculo_id: 'vei-compass',
    veiculo_desc: 'Jeep Compass 2022 - PQR-9S22',
    tecnico: 'Diego Ferreira',
    prioridade: 'normal',
    total: money(780),
    data_abertura: daysAgo(6),
    data_conclusao: daysAgo(1),
    observacoes: 'Entrega realizada com checklist assinado.',
    itens: [item('Troca de óleo', 1, 290, 'concluido'), item('Filtro', 1, 140, 'concluido'), item('Mão de obra', 1, 350, 'concluido')],
  },
  {
    id: 'os-088',
    numero: 'OS-2026-088',
    status: 'aguardando_peca',
    pagamento_status: 'pendente',
    cliente_id: 'cli-ricardo',
    cliente_nome: 'Ricardo Almeida',
    veiculo_id: 'vei-hrv',
    veiculo_desc: 'Honda HR-V 2022 - GHI-4J22',
    tecnico: 'Paulo Henrique',
    prioridade: 'normal',
    total: money(1420),
    data_abertura: daysAgo(2),
    data_conclusao: null,
    observacoes: 'Aguardando embreagem.',
    itens: [item('Diagnóstico embreagem', 1, 180, 'concluido'), item('Kit embreagem', 1, 920, 'pendente'), item('Mão de obra', 1, 320, 'pendente')],
  },
  {
    id: 'os-086',
    numero: 'OS-2026-086',
    status: 'concluida',
    pagamento_status: 'pago',
    cliente_id: 'cli-juliana',
    cliente_nome: 'Juliana Martins',
    veiculo_id: 'vei-pulse',
    veiculo_desc: 'Fiat Pulse 2023 - MNO-8P23',
    tecnico: 'Diego Ferreira',
    prioridade: 'baixa',
    total: money(180),
    data_abertura: daysAgo(12),
    data_conclusao: daysAgo(9),
    observacoes: 'Diagnóstico simples concluído e entregue.',
    itens: [item('Diagnóstico', 1, 180, 'concluido')],
  },
];

export const demoFinanceiro = {
  faturamento_mes: money(28640),
  ticket_medio: money(1190),
  total_receber: money(6820),
  total_recebido: money(21820),
  lucro: money(11456),
  os_concluidas: 24,
  lancamentos_count: 5,
  faturamento_semanal: [7200, 8400, 6800, 6240],
};

export const demoLancamentos = [
  { id: 'fin-1', data: daysAgo(6), descricao: 'Recebimento OS-2026-090', categoria: 'Serviços', forma: 'PIX', tipo: 'entrada', valor: 780, status: 'confirmado' },
  { id: 'fin-2', data: daysAgo(5), descricao: 'Entrada frota Marcelo Souza', categoria: 'Serviços', forma: 'Cartão', tipo: 'entrada', valor: 1850, status: 'confirmado' },
  { id: 'fin-3', data: daysAgo(4), descricao: 'Compra de peças linha freio', categoria: 'Peças', forma: 'Boleto', tipo: 'saida', valor: 1240, status: 'confirmado' },
  { id: 'fin-4', data: daysAgo(2), descricao: 'Aluguel + utilities', categoria: 'Fixos', forma: 'Débito', tipo: 'saida', valor: 2184, status: 'confirmado' },
  { id: 'fin-5', data: daysAgo(1), descricao: 'Recebimento revisões balcão', categoria: 'Serviços', forma: 'PIX', tipo: 'entrada', valor: 3420, status: 'confirmado' },
];

export const demoFaturamentoMensal = [
  { mes: 'Dez', valor: 21800 },
  { mes: 'Jan', valor: 23200 },
  { mes: 'Fev', valor: 24160 },
  { mes: 'Mar', valor: 25740 },
  { mes: 'Abr', valor: 26990 },
  { mes: 'Mai', valor: 28640 },
];

export const demoOsPorStatus = [
  { status: 'Abertas', valor: 0, color: '#D6D3CB' },
  { status: 'Em andamento', valor: 1, color: '#1C3F5E' },
  { status: 'Aguard. peça', valor: 1, color: '#8A5A0A' },
  { status: 'Concluídas', valor: 2, color: '#1A6B3A' },
];

export const demoDashboardStats = {
  os_abertas: 2,
  os_concluidas_hoje: 1,
  orcamentos_pendentes: 1,
  veiculos_em_atendimento: 3,
  clientes_inativos: 2,
  faturamento: money(28640),
  contas_receber: money(6820),
  ticket: money(1190),
  taxa_aprovacao: 74,
  os_semana: 6,
  servicos_top: [
    { nome: 'Troca de Oleo', total: 38 },
    { nome: 'Freios', total: 22 },
    { nome: 'Suspensao', total: 17 },
    { nome: 'Eletrica', total: 14 },
    { nome: 'Ar', total: 9 },
  ],
};

export const demoEquipe = [
  {
    id: 'eq-paulo',
    nome: 'Paulo Henrique',
    email: 'paulo@autocentersupremo.com.br',
    telefone: '(11) 99111-1101',
    role: 'tecnico',
    ativo: true,
    especialidade: 'Mecanica Geral',
    os_ativas: 2,
    os_concluidas_mes: 14,
    ultimo_login: daysAgo(0),
  },
  {
    id: 'eq-diego',
    nome: 'Diego Ferreira',
    email: 'diego@autocentersupremo.com.br',
    telefone: '(11) 99111-1102',
    role: 'tecnico',
    ativo: true,
    especialidade: 'Eletrica',
    os_ativas: 1,
    os_concluidas_mes: 10,
    ultimo_login: daysAgo(0),
  },
  {
    id: 'eq-aline',
    nome: 'Aline Rocha',
    email: 'aline@autocentersupremo.com.br',
    telefone: '(11) 99111-1103',
    role: 'recepcao',
    ativo: true,
    especialidade: 'Atendimento',
    os_ativas: 0,
    os_concluidas_mes: 0,
    ultimo_login: daysAgo(0),
  },
  {
    id: 'eq-roberto',
    nome: 'Roberto Nascimento',
    email: 'roberto@autocentersupremo.com.br',
    telefone: '(11) 99111-1104',
    role: 'admin',
    ativo: true,
    especialidade: 'Admin',
    os_ativas: 0,
    os_concluidas_mes: 0,
    ultimo_login: daysAgo(1),
  },
];

export const demoAIInsights = [
  {
    id: 'ai-1',
    tipo: 'retorno',
    prioridade: 'alta',
    titulo: 'Fernanda Costa 90d sem retornar',
    descricao: 'Cliente com Polo parado sem retorno recente. Forte chance de recuperação com abordagem consultiva.',
    acao_sugerida: 'Enviar campanha de retorno com convite para check-up rápido.',
    cliente_nome: 'Fernanda Costa',
    veiculo: 'VW Polo 2020 - DEF-5K20',
    mensagem_sugerida: 'Ola Fernanda! Percebemos que ja faz um tempo desde sua ultima visita ao Auto Center Supremo. Seu Polo merece um check-up! Que tal agendar uma revisao rapida?',
    impacto_estimado: 780,
    lista_clientes: ['Fernanda Costa'],
  },
  {
    id: 'ai-2',
    tipo: 'orcamento',
    prioridade: 'alta',
    titulo: 'Orcamento ORC-2026-042 sem resposta 4d',
    descricao: 'Orçamento importante parado para Corolla com risco técnico se a troca for adiada.',
    acao_sugerida: 'Enviar follow-up educativo com urgência técnica.',
    cliente_nome: 'Ricardo Almeida',
    veiculo: 'Toyota Corolla 2021 - BRA-2E19',
    mensagem_sugerida: 'Ola Ricardo! O orcamento ORC-2026-042 do seu Corolla segue pendente. A troca da correia dentada e da bomba dagua evita danos mais caros ao motor. Quer que eu reserve horario para voce?',
    impacto_estimado: 2340,
    lista_clientes: ['Ricardo Almeida'],
  },
  {
    id: 'ai-3',
    tipo: 'revisao',
    prioridade: 'media',
    titulo: 'Honda HR-V 22.100km perto dos 25.000km',
    descricao: 'Veículo muito próximo da próxima revisão programada.',
    acao_sugerida: 'Antecipar contato e travar agenda para revisão preventiva.',
    cliente_nome: 'Ricardo Almeida',
    veiculo: 'Honda HR-V 2022 - GHI-4J22',
    mensagem_sugerida: 'Ola Ricardo! Sua Honda HR-V esta chegando perto dos 25.000km. Podemos antecipar a revisao preventiva e evitar filas na agenda. Posso te mandar horarios?',
    impacto_estimado: 640,
    lista_clientes: ['Ricardo Almeida'],
  },
  {
    id: 'ai-4',
    tipo: 'inativo',
    prioridade: 'alta',
    titulo: 'Carlos Eduardo Ramos inativo +130d',
    descricao: 'Cliente sem recorrência recente, bom perfil para reativação com oferta de diagnóstico.',
    acao_sugerida: 'Oferecer diagnóstico grátis com janela curta para urgência.',
    cliente_nome: 'Carlos Eduardo Ramos',
    veiculo: 'Sem veiculo ativo no cadastro',
    mensagem_sugerida: 'Ola Carlos! Faz um tempo desde seu ultimo atendimento no Auto Center Supremo. Estamos com diagnostico gratis para reativar clientes da casa. Quer aproveitar e passar aqui esta semana?',
    impacto_estimado: 920,
    lista_clientes: ['Carlos Eduardo Ramos'],
  },
  {
    id: 'ai-5',
    tipo: 'os_parada',
    prioridade: 'media',
    titulo: 'OS-2026-088 aguardando peca 2d',
    descricao: 'Cliente ainda sem atualização clara sobre prazo da embreagem.',
    acao_sugerida: 'Mandar atualização proativa para reduzir ansiedade e evitar desgaste.',
    cliente_nome: 'Ricardo Almeida',
    veiculo: 'Honda HR-V 2022 - GHI-4J22',
    mensagem_sugerida: 'Ola Ricardo! Atualizando sua OS-2026-088: estamos aguardando a chegada da embreagem para concluir o servico da HR-V. Assim que a peca entrar, priorizamos a montagem e te avisamos imediatamente.',
    impacto_estimado: 1900,
    lista_clientes: ['Ricardo Almeida'],
  },
];

export const demoAtividade = [
  { id: 'atv-1', quando: daysAgo(0), texto: 'Aline Rocha confirmou entrega da OS-2026-090 para Patricia Lima.' },
  { id: 'atv-2', quando: daysAgo(0), texto: 'Paulo Henrique iniciou a etapa de freios da OS-2026-091.' },
  { id: 'atv-3', quando: daysAgo(1), texto: 'Orcamento ORC-2026-042 enviado ao Ricardo Almeida via WhatsApp.' },
  { id: 'atv-4', quando: daysAgo(1), texto: 'Diego Ferreira concluiu diagnostico do Fiat Pulse da Juliana.' },
  { id: 'atv-5', quando: daysAgo(2), texto: 'Marcelo Souza aprovou o orçamento ORC-2026-041 da S10.' },
];

export const demoProximasAcoes = [
  { id: 'acao-1', texto: 'Fazer follow-up do ORC-2026-042 com Ricardo Almeida.', quando: 'Hoje' },
  { id: 'acao-2', texto: 'Disparar mensagem de retorno para Fernanda Costa.', quando: 'Hoje' },
  { id: 'acao-3', texto: 'Atualizar cliente da OS-2026-088 sobre chegada da embreagem.', quando: 'Hoje' },
  { id: 'acao-4', texto: 'Antecipar revisão da Honda HR-V perto dos 25 mil km.', quando: 'Amanhã' },
];

export const demoMasterKpis = {
  totalEmpresas: 14,
  ativas: 12,
  trial: 2,
  suspensas: 0,
  mrr: money(4186),
  churnMes: 2.4,
};

export const demoEmpresas = [
  { id: 'emp-1', nome: 'Auto Center Supremo', cidade: 'SP', plano: 'Profissional', status: 'ativa', percentual: 100, mrr: 28640, owner_email: 'contato@autocentersupremo.com.br' },
  { id: 'emp-2', nome: 'Mecanica do Ze', cidade: 'Campinas', plano: 'Basico', status: 'ativa', percentual: 100, mrr: 9800, owner_email: 'ze@mecanicadoze.com.br' },
  { id: 'emp-3', nome: 'EletricaCar Premium', cidade: 'Ribeirao', plano: 'Profissional', status: 'ativa', percentual: 100, mrr: 21400, owner_email: 'contato@eletricacar.com.br' },
  { id: 'emp-4', nome: 'AutoPro Revisoes', cidade: 'BH', plano: 'Trial', status: 'trial', percentual: 60, mrr: 2100, owner_email: 'sucesso@autopro.com.br' },
  { id: 'emp-5', nome: 'Centro Automotivo Norte', cidade: 'Manaus', plano: 'Basico', status: 'ativa', percentual: 100, mrr: 7200, owner_email: 'contato@canorte.com.br' },
  { id: 'emp-6', nome: 'Oficina Veloz', cidade: 'Guarulhos', plano: 'Basico', status: 'ativa', percentual: 100, mrr: 6400, owner_email: 'oficina@veloz.com.br' },
  { id: 'emp-7', nome: 'Garage Prime', cidade: 'Santo Andre', plano: 'Profissional', status: 'ativa', percentual: 100, mrr: 13100, owner_email: 'prime@garageprime.com.br' },
  { id: 'emp-8', nome: 'Master Diesel', cidade: 'Osasco', plano: 'Profissional', status: 'ativa', percentual: 100, mrr: 15400, owner_email: 'diesel@master.com.br' },
  { id: 'emp-9', nome: 'Full Car Service', cidade: 'Santos', plano: 'Basico', status: 'ativa', percentual: 100, mrr: 8700, owner_email: 'contato@fullcar.com.br' },
  { id: 'emp-10', nome: 'AutoBox Leste', cidade: 'SP', plano: 'Basico', status: 'ativa', percentual: 100, mrr: 7600, owner_email: 'leste@autobox.com.br' },
  { id: 'emp-11', nome: 'Oficina Central', cidade: 'Sorocaba', plano: 'Profissional', status: 'ativa', percentual: 100, mrr: 14300, owner_email: 'central@oficina.com.br' },
  { id: 'emp-12', nome: 'Top Suspensao', cidade: 'Jundiai', plano: 'Basico', status: 'ativa', percentual: 100, mrr: 5900, owner_email: 'top@suspensao.com.br' },
  { id: 'emp-13', nome: 'RevisaCar Oeste', cidade: 'Barueri', plano: 'Trial', status: 'trial', percentual: 45, mrr: 0, owner_email: 'trial@revisacar.com.br' },
  { id: 'emp-14', nome: 'Auto Clinica Sul', cidade: 'Sao Bernardo', plano: 'Profissional', status: 'ativa', percentual: 100, mrr: 12800, owner_email: 'sul@autoclinica.com.br' },
];
