import {Query,type QuerySpec} from '../../shared/query';import{schema,jsonFields}from'./schema';
export type SQL={sql:(q:string,args?:any[])=>Promise<{rows:any[]}>;batch:(s:{sql:string,args?:any[]}[],mode?:'read'|'write')=>Promise<any>};
export type Identity={userId:string;email?:string;master:boolean;empresaId?:string;role?:string};
const q=(s:string)=>'"'+s+'"';const val=(v:any)=>typeof v==='boolean'?Number(v):v!==null&&typeof v==='object'?JSON.stringify(v):v??null;
const writers:Record<string,string[]>={empresa:['owner','admin'],empresa_user:['owner','admin'],cliente:['owner','admin','recepcao'],veiculo:['owner','admin','recepcao'],orcamento:['owner','admin','recepcao'],ordem_servico:['owner','admin','recepcao','tecnico'],lancamento:['owner','admin','financeiro'],servico_referencia:['owner','admin'],horario_funcionamento:['owner','admin'],solicitacao:['owner','admin','recepcao']};
export function decode(t:string,r:any){return Object.fromEntries(Object.entries(r).map(([k,v])=>{if(schema[t]?.[k]==='BOOLEAN')return[k,v===true||v===1||v==='1'];if(schema[t]?.[k]==='REAL'&&v!==null)return[k,Number(v)];if(jsonFields.has(k)&&typeof v==='string'){try{return[k,JSON.parse(v)]}catch{}}return[k,v]}))}
export class Database{
 constructor(public sql:SQL,public identity:Identity){}from(table:string){return new Query(table,s=>this.execute(s))}
 async scope(t:string,write:boolean){const u=this.identity;if(!schema[t]||['users','profiles','user_roles','template_owner'].includes(t))throw Error('Tabela indisponível');if(!u.userId)throw Error('Autenticação necessária');if(t==='app_config')throw Error('Configuração protegida');
 if(u.master){if(u.empresaId)return{clause:(t==='empresa'?'id':'empresa_id')+'=?',args:[u.empresaId]};if(t!=='empresa')throw Error('Selecione uma oficina');return{clause:'1=1',args:[]}};if(!u.empresaId)throw Error('Oficina não encontrada');const ac=(await this.sql.sql('SELECT status,status_cobranca,trial_ate FROM empresa WHERE id=?',[u.empresaId])).rows[0];if(t!=='empresa'&&(!ac||['inativo'].includes(ac.status)||['suspenso','cancelado'].includes(ac.status_cobranca)||ac.status==='trial'&&ac.trial_ate&&ac.trial_ate<new Date().toISOString().slice(0,10)))throw Error('Oficina suspensa; fale com o administrador');
 if(write&&!writers[t]?.includes(u.role||''))throw Error('Permissão insuficiente');if(!write&&['lancamento'].includes(t)&&!['owner','admin','financeiro'].includes(u.role||''))throw Error('Permissão insuficiente');return{clause:(t==='empresa'?'id':'empresa_id')+'=?',args:[u.empresaId]}}
 async execute(input:QuerySpec):Promise<any>{try{const s=structuredClone(input),t=s.table,write=s.action!=='select';if(!['select','insert','update','delete'].includes(s.action))throw Error('Operação inválida');const col=(k:string)=>{if(!schema[t]?.[k])throw Error('Coluna inválida');return q(k)};const scope=await this.scope(t,write),args:any[]=[...scope.args],where=[scope.clause];if(!Array.isArray(s.filters)||s.filters.length>30)throw Error('Filtro inválido');
 for(const f of s.filters){const k=col(f.key);if(f.op==='in'){if(!Array.isArray(f.value)||f.value.length>1000)throw Error('Filtro inválido');where.push(f.value.length?k+' IN ('+f.value.map(()=>'?').join(',')+')':'0=1');args.push(...f.value.map(val));continue}if(f.op==='notnull'){where.push(k+' IS NOT NULL');continue}const op:Record<string,string>={eq:'=',neq:'!=',gt:'>',gte:'>=',lt:'<',lte:'<=',is:'IS',ilike:'LIKE'};if(!op[f.op])throw Error('Operador inválido');where.push(k+' '+op[f.op]+' ?');args.push(val(f.value))}
 const clause=where.join(' AND '),limit=Math.min(5000,Math.max(0,Number(s.limit??1000))),offset=Math.max(0,Number(s.offset??0));if(!Number.isInteger(limit)||!Number.isInteger(offset))throw Error('Paginação inválida');const selected=s.columns==='*'||!s.columns?null:s.columns.split(',').map(x=>x.trim());selected?.forEach(col);let rows:any[]=[],count=0;
 if(!write){count=Number((await this.sql.sql('SELECT COUNT(*) AS total FROM '+q(t)+' WHERE '+clause,args)).rows[0]?.total||0);if(!s.head)rows=(await this.sql.sql('SELECT * FROM '+q(t)+' WHERE '+clause+(s.orders?.length?' ORDER BY '+s.orders.map(o=>col(o.key)+(o.ascending?' ASC':' DESC')).join(','):'')+' LIMIT ? OFFSET ?',[...args,limit,offset])).rows}
 else{if(s.action!=='insert'&&!s.filters.length)throw Error('Alteração exige filtro explícito');if(t==='app_config')throw Error('Configuração protegida');if(t==='empresa'&&s.action==='insert')throw Error('Use o cadastro de oficina');
 if(s.action==='delete'){if(['empresa','ordem_servico','empresa_user'].includes(t))throw Error('Registro protegido; altere o status');if(t==='lancamento'&&(await this.sql.sql('SELECT os_id FROM lancamento WHERE '+clause,args)).rows.some((r:any)=>r.os_id))throw Error('Recebimento vinculado: altere pagamento na OS');rows=(await this.sql.sql('DELETE FROM '+q(t)+' WHERE '+clause+' RETURNING *',args)).rows}
 else{const payloads=Array.isArray(s.payload)?s.payload:[s.payload];if(payloads.length!==1)throw Error('Salve um registro por vez');const raw=payloads[0];if(!raw||typeof raw!=='object')throw Error('Dados inválidos');const row={...raw};Object.keys(row).forEach(col);const old=s.action==='update'?(await this.sql.sql('SELECT * FROM '+q(t)+' WHERE '+clause,args)).rows:[];if(old.length>1)throw Error('Atualize um registro por vez');if(s.action==='update'&&!old.length)return{data:[],error:null,count:0};if(s.action==='update'){delete row.id;delete row.created_at;delete row.empresa_id;if(schema[t].updated_at)row.updated_at=new Date().toISOString()}
 if(!this.identity.master){if(t==='empresa'&&Object.keys(row).some(k=>!['nome','slug','slogan','cnpj','telefone','email','endereco','cor_primaria','cor_secundaria','logo_url','sobre','whatsapp','anos_mercado','vitrine_ativa','onboarding_concluido','updated_at'].includes(k)))throw Error('Campo protegido');if(t!=='empresa'&&s.action==='insert'){if(row.empresa_id&&row.empresa_id!==this.identity.empresaId)throw Error('Oficina inválida');row.empresa_id=this.identity.empresaId}}
 const merged={...(old[0]||{}),...row};if(t!=='empresa'&&!(await this.sql.sql('SELECT id FROM empresa WHERE id=?',[merged.empresa_id])).rows.length)throw Error('Oficina inválida');
 if(this.identity.master&&this.identity.empresaId&&t!=='empresa'&&merged.empresa_id!==this.identity.empresaId)throw Error('Oficina inválida');
 if(t==='empresa'&&['id','owner_email','owner_nome'].some(k=>Object.hasOwn(row,k)))throw Error('Proprietário protegido');
 if(['empresa','cliente','servico_referencia'].includes(t)&&(!String(merged.nome||'').trim()||String(merged.nome).length>200))throw Error('Nome inválido');
 if(t==='empresa'&&row.logo_url&&!/^data:image\/(png|jpeg|webp);base64,[A-Za-z0-9+/=]+$/.test(row.logo_url)&&!/^https:\/\//.test(row.logo_url))throw Error('Imagem inválida');if(t==='empresa'&&String(row.logo_url||'').length>220000)throw Error('Imagem muito grande');if(t==='empresa'&&row.slug&&!/^[a-z0-9-]{2,60}$/.test(row.slug))throw Error('Endereço público inválido');
 if(t==='empresa_user'){if(old[0]?.role==='owner'||merged.role==='owner'||row.auth_user_id)throw Error('Acesso proprietário protegido');if(!['admin','tecnico','recepcao','financeiro'].includes(merged.role))throw Error('Função inválida');row.email=String(merged.email||'').trim().toLowerCase();if(!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(row.email))throw Error('Email inválido');row.auth_user_id=null;}
 if(t==='veiculo'){if(!String(merged.marca||'').trim()||!String(merged.modelo||'').trim()||!String(merged.placa||'').trim())throw Error('Informe marca, modelo e placa');row.placa=String(merged.placa).replace(/[^A-Za-z0-9]/g,'').toUpperCase();if(row.placa.length<5||row.placa.length>10)throw Error('Placa inválida');}
 if(merged.cliente_id){const cli=(await this.sql.sql('SELECT nome FROM cliente WHERE id=? AND empresa_id=?',[merged.cliente_id,merged.empresa_id])).rows[0];if(!cli)throw Error('Cliente fora da oficina');if(schema[t].cliente_nome)row.cliente_nome=cli.nome;}
 if(['orcamento','ordem_servico'].includes(t)){const veic=(await this.sql.sql('SELECT marca,modelo,placa,cliente_id FROM veiculo WHERE id=? AND empresa_id=?',[merged.veiculo_id,merged.empresa_id])).rows[0];if(!veic||veic.cliente_id!==merged.cliente_id)throw Error('Veículo de outro cliente');row.veiculo_desc=veic.marca+' '+veic.modelo+' — '+veic.placa;const items=typeof merged.itens==='string'?JSON.parse(merged.itens):merged.itens||[];if(!Array.isArray(items)||items.length>100)throw Error('Itens inválidos');let cents=0;for(const item of items){if(!String(item.descricao||'').trim()||!Number.isFinite(Number(item.quantidade))||Number(item.quantidade)<=0||Number(item.quantidade)>10000||!Number.isFinite(Number(item.valor))||Number(item.valor)<0||Number(item.valor)>1e7)throw Error('Item inválido');cents+=Math.round(Number(item.valor)*100)*Number(item.quantidade)}row.total=Math.round(cents)/100;row.itens=items;
 if(t==='orcamento'){if(!['pendente','aprovado','recusado'].includes(merged.status||'pendente'))throw Error('Status inválido');if(row.convertido_em_os)throw Error('Use converter orçamento');if(old[0]?.convertido_em_os)throw Error('Orçamento já convertido; edite a OS');}
 if(t==='ordem_servico'){if(!this.identity.master&&this.identity.role==='tecnico'){if(s.action!=='update')throw Error('Técnico só atualiza checklist');const previous=JSON.parse(old[0]?.itens||'[]');if(items.length!==previous.length||items.some((it:any,i:number)=>it.descricao!==previous[i].descricao||Number(it.valor)!==Number(previous[i].valor)||Number(it.quantidade)!==Number(previous[i].quantidade)))throw Error('Valores e itens protegidos para técnico');}if(!['aberta','em_andamento','aguardando_peca','concluida','cancelada'].includes(merged.status||'aberta')||!['pendente','pago','parcial'].includes(merged.pagamento_status||'pendente')||!['baixa','normal','alta'].includes(merged.prioridade||'normal'))throw Error('Status inválido');if(Object.hasOwn(row,'orcamento_id'))throw Error('Use converter orçamento');if(!this.identity.master&&this.identity.role==='tecnico'&&Object.keys(raw).some(k=>!['status','itens','data_conclusao'].includes(k)))throw Error('Técnico só atualiza andamento e checklist');if(merged.tecnico&&!(await this.sql.sql('SELECT id FROM empresa_user WHERE nome=? AND empresa_id=? AND ativo=1',[merged.tecnico,merged.empresa_id])).rows.length)throw Error('Técnico fora da oficina');if(row.status==='concluida')row.data_conclusao=new Date().toISOString().slice(0,10);}
 }
 if(t==='lancamento'){if(old[0]?.os_id||row.os_id)throw Error('Recebimento vinculado: altere pagamento na OS');if(!['entrada','saida'].includes(merged.tipo||'entrada')||!['pendente','confirmado','cancelado'].includes(merged.status||'pendente'))throw Error('Status financeiro inválido');if(!Number.isFinite(Number(merged.valor))||Number(merged.valor)<=0||Number(merged.valor)>1e8)throw Error('Valor inválido');row.valor=Math.round(Number(merged.valor)*100)/100;}
 for(const k of ['ano','quilometragem','valor_referencia','duracao_min','valor','anos_mercado'])if(row[k]!=null&&(!Number.isFinite(Number(row[k]))||Number(row[k])<0))throw Error('Valor inválido: '+k);
 for(const k of ['data','data_abertura','data_prevista','data_conclusao','proxima_revisao','ultima_revisao','validade'])if(row[k]&&!/^\d{4}-\d{2}-\d{2}$/.test(row[k]))throw Error('Data inválida');
 if(t==='solicitacao'&&(s.action!=='update'||Object.keys(raw).some(k=>k!=='status')||!['novo','em_contato','concluido','cancelado'].includes(row.status)))throw Error('Apenas o status da solicitação pode ser alterado');
 if(s.action==='insert'&&!row.id)row.id=crypto.randomUUID();const keys=Object.keys(row),params=keys.map(k=>val(row[k]));rows=(await this.sql.sql(s.action==='update'?'UPDATE '+q(t)+' SET '+keys.map(k=>col(k)+'=?').join(',')+' WHERE '+clause+' RETURNING *':'INSERT INTO '+q(t)+' ('+keys.map(col).join(',')+') VALUES ('+keys.map(()=>'?').join(',')+') RETURNING *',s.action==='update'?[...params,...args]:params)).rows
 }count=rows.length}
 const data=rows.map(r=>{const d=decode(t,r);if(t==='empresa_user')delete d.auth_user_id;return selected?Object.fromEntries(selected.map(k=>[k,d[k]])):d});if(s.cardinality==='one'&&data.length!==1)throw Error('Registro não encontrado');return{data:s.head?null:s.cardinality?data[0]??null:data,error:null,count}
 }catch(e:any){return{data:null,error:{message:e.message},count:0}}}
}
